services:
  api:
    build:
      context: ./backend
    container_name: drug-service-api-local
    environment:
      DATABASE_URL: postgresql://drug_service:drug_service_local@host.docker.internal:5433/drug_service
      APP_NAME: Drug Service API
    ports:
      - "8010:8000"
